<?php

// Check if exists an autoload generated by composer
if (file_exists(__DIR__.'/../vendor/.composer/autoload.php') == false) {

    echo 'You must setup the dependencies for the project using Composer.';
    exit;

}

// Requires the composer's autoload
require_once __DIR__.'/../vendor/.composer/autoload.php';


/**
 * Load the configuration file
 ******************************************************************************/
if (file_exists(__DIR__.'/../config.yml') == false) {
    echo 'You must configure your environment through the config.yml';
    exit;
}

try {

    $yaml = new Symfony\Component\Yaml\Parser();
    $configurations = $yaml->parse(file_get_contents(__DIR__.'/../config.yml'));
    unset($yaml);

    if (isset($configurations['cache.dir'])) {
        $configurations['cache.dir'] = __DIR__.'/../'.$configurations['cache.dir'];
    }

} catch (Symfony\Component\Yaml\Exception\ParseException $e) {

    echo 'Unable to parse the configuration file: ' . $e->getMessage();
    exit;

}


/**
 * Init
 ******************************************************************************/
$app = new Silex\Application();
$app->register(new Silex\Provider\SessionServiceProvider());
$app->register(new Silex\Provider\TwigServiceProvider(), array(
    'twig.path' => __DIR__ . '/../src/GitHubSummary/Resources/Views',
));
// Put the configurations on the app
foreach ($configurations as $configKey => $configValue) {
    $app[$configKey] = $configValue;
}

/**
 * Filters
 *******************************************************************************/
$app->before(function ($request) use($app) {
    // Starts the session
    $request->getSession()->start();
    // Create an instance of the cache helper
    $cache = new GitHubSummary\Helpers\Cache($app['cache.dir']);
    // Declare the github's service
    $app['github'] = new GitHubSummary\Services\GitHub(
        $cache,
        $app['session']->get('access_token')
    );
});

/**
 * Middlewares
 ******************************************************************************/
$mustBeLogged = function ($request) use ($app) {
    if (!$app['session']->has('access_token'))
        return $app->redirect('/login');
};

/**
 * Routes
 ******************************************************************************/
$app->get('/login', function() use($app)
{
    return $app['twig']->render('login.twig', array(
        'url_login' => $app['github']->getAuthorizeUrl($app['github.client_id'])
    ));
})
->bind('login');


$app->get('/login/callback', function() use($app)
{
    $token = $app['github']->getAccessToken(
        $app['github.client_id'],
        $app['github.client_secret'],
        $app['request']->get('code')
    );
    if($token) {
        $app['session']->set('access_token', $token);
        $app['session']->set('user', $app['github']->getUser());
        return $app->redirect('/');
    }

    return $app->redirect('/error');
})
->bind('login_calback');


$app->get('/logout', function() use($app)
{
    $app['session']->clear();
    return $app->redirect('/login');
})
->bind('logout');


$app->get('/', function() use($app)
{
    return $app['twig']->render('index.twig', array(
        'repositories' => $app['github']->getWatchedRepositories(),
        'followingUsers' => $app['github']->getFollowingUsers(),
    ));
})
->bind('home')
->middleware($mustBeLogged);


$app->get('/events', function() use($app)
{
    $user = $app['session']->get('user');
    return $app['twig']->render('events.twig', array(
        'events' => (array) $app['github']->getEvents($user['login'])
    ));
})
->bind('events')
->middleware($mustBeLogged);


$app->run();
